### ISSUE TITLE
`lake build*` broken when elan defaults to other toolchains

### ISSUE THREAD

**Issue by xubaiw** [tydeu/lean4-lake#3] opened 2021-07-28 03:44 UTC
Lake revision: 71defa066dd845a31d19547f1a3e01f79c5fc8d9
Lake works well with Lean toolchains of same version, which is currently "leanprover/lean4:nightly-2021-07-09".
But when we default to other Lean version, the `lake build*` command got broken
```sh
# built with leanprover/lean4:nightly-2021-07-09
$ ls
Abcd.lean    package.lean
$ lake build-bin
> LEAN_PATH=./build/lib lean -R . -o ./build/lib/Abcd.olean -c ./build/ir/Abcd.c ././Abcd.lean
> leanc -c -o ./build/ir/Abcd.o ./build/ir/Abcd.c
> leanc -o ./build/bin/abcd ./build/ir/Abcd.o
$ rm -rf build 

# when switch to latest nightly
$ elan default leanprover/lean4:nightly  # 4.0.0-nightly-2021-07-23
$ lake build-bin  # `lake build` produces the same effect
[1]    5735 segmentation fault  Lake build-bin
```

**Comment by tydeu** [comment] 2021-07-28 12:15
It segfaults?! That seems like it could very well be an issue with the newer Lean version rather than Lake. There are no external C bindings in Lake's code, so it should be memory safe as long as Lean is memory safe. Thus I would generally attribute a segfault to Lean itself rather than Lake. Though the buggy Lean version in question could be either Lake's or the newer Lean.

I'll spend some time trying to reproduce and debug this.

**Comment by tydeu** [comment] 2021-07-29 14:15
As I mentioned in the [Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Cross-version.20olean.20imports/near/247511702) this is likely a Lean bug, so it will probably have to be resolved by them.

I did bump the Lean version of Lake, though, so that it now defaults to a newer nightly.

**Comment by tydeu** [comment] 2021-09-12 15:30
This issue has been idle for a while, and since it is essentially a bug with Lean not Lake, I am closing this issue.

**Closed by tydeu** 2021-09-12 15:30 UTC
Labels: bug
