### ISSUE TITLE
`lake build-bin` hangs in this directory structure

### ISSUE THREAD

**Issue by tydeu** [tydeu/lean4-lake#5] opened 2021-07-29 13:55 UTC
_Originally posted by @xubaiw in https://github.com/tydeu/lean4-lake/issues/4#issuecomment-888777694_

> There's still a bug in revision 39c463636b17f690caa9cb5d1fa686a80698d936.
> The `lean build-bin` command got stuck when I run it in "./lake".
> ```sh
> $ tree 
> .
> ├── Foo
> │   └── Bar.lean
> ├── Foo.lean
> ├── lake
> │   └── package.lean
> └── leanpkg.toml
> ```
> And my "package.lean" config is like this
> ```Lean
> def package : Lake.PackageConfig := {
>   name := "foo"
>   version := "0.1"
>   leanVersion := "leanprover/lean4:nightly-2021-07-28"
>   rootDir := ".."
>   buildDir := "../build"
> }
> ```
> The command got stuck with no output and I am not sure where the problem comes from.
> 
> The `lake build-bin` command run successfully when I remove the "leanpkg.toml" file in the root directory.
> ```shell
> $ tree -I build                   
> .
> ├── Foo
> │   └── Bar.lean
> ├── Foo.lean
> ├── lake
> │   └── package.lean
> └── leanpkg.toml
> 
> $ rm leanpkg.toml   # remove leanpkg.toml in root dir
> $ cd lake && lake build-bin
> > LEAN_PATH=./../build/lib lean -R ./.. -o ./../build/lib/Foo.olean -c ./../build/ir/Foo.c ./../Foo.lean
> > leanc -c -o ./../build/ir/Foo.o ./../build/ir/Foo.c
> > leanc -o ./../build/bin/foo ./../build/ir/Foo.o
> ```

**Comment by tydeu** [comment] 2021-07-29 14:03
Likely a duplicate of #3.

**Comment by xubaiw** [comment] 2021-08-02 03:11
> Likely a duplicate of #3.

I myself cannot reproduce this issue now, and it have to be a problem from Lean. Please close this issue. Thanks!

**Closed** 2021-08-02 03:28 UTC
Labels: bug
